---

 - name: Provision an EC2 Instance
   hosts: local
   connection: local
   gather_facts: False
   tags: provisioning

   # Variables for provisioning the EC2 Instance
   vars:
      instance_type: t2.micro
      security_group: ansible-webserver 
      image: ami-43a15f3e  # This is an AMI for Ubuntu 16
      keypair: awstest # This is the key you imported to AWS Key Pair Console
      region: eu-west-2
      count: 1

   # Task that will be used to Launch/Create an EC2 Instance
   tasks:

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: AWSTEST
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall

      - name: Launch the new EC2 Instance.
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{ count }}
        register: ec2

      - name: Wait for SSH to come up
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: "{{ ec2.instances }}"

      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: webserver

      - name: Add the newly created EC2 instance IP to the ansible-playbook in-Memory inventory (webserver group)
        add_host:
          name: "{{ item.public_ip }}"
          groups: webserver
        with_items: "{{ ec2.instances }}"
     
      - name: Add the newly created EC2 instance IP to the local host inventory file (stored in your current directory)
        local_action: lineinfile
                      dest="hosts"
                      insertafter="webserver"
                      line={{ item.public_ip }}
        with_items: "{{ ec2.instances }}"
       
      - name: run another play
        command: ansible-playbook /etc/ansible/jenkins.yml

